### ISSUE TITLE
Time stamping

### ISSUE THREAD

**Issue by BaptisteVandecrux** [EnviDat/monitoring-backend#2]
Time stamping: Note that at the moment each hourly interval is stamped with the end time of the interval. This is different from PROMICE standards which gives the beginning of the interval as time stamps

Ionut:
>I assume this is how the logger is configured - as far as I can tell, the station takes measurements over an hour, then averages those measurements and then sends/logs the averaged values. In the PROMICE standard you then record values in the "future" hour instead of the "past" hour. Anyway, we can modify the timestamp if necessary, but I would need to discuss this issue with Derek first, just to make sure I understand everything correctly. (BTW, the GC-Net approach sounds reasonable to me... but Derek is the expert.) 

Derek:
> I agree that the GC-net version of time-stamping is more intuitive. Of course we can apply a 1hr time shift if you are set on the PROMICE standard.

**Comment by BaptisteVandecrux** [comment]
I am not sure that using the end of the hourly interval is that intuitive:
From the data-user point of view, if I have a punctual measurement made at a GC-Net site at 12:15 (e.g. snow pit, remote sensing...) and wanted to know the weather conditions then, I would tend to look at the entry for "12:00" in the weather data file.

Additionally PROMICE will have to provide the data averaged on daily and monthly periods. When averaging data from 2020-01-01 00:00:00 to 2020-01-02 00:00:00, would you then use "2020-01-02 00:00:00" as a time stamp?

**Comment by mankoff** [comment]
I agree that end-of-hour is less intuitive. It makes sense to me from a computer perspective - things accumulate into a bucket. The bucket is labeled when the accumulation stops. But from an environmental perspective, I think things are normally timestamped at the beginning of the collection period. 

Some weather sites (http://www.vejrcentral.dk/en/europe/denmark/weather-copenhagen/details/T/ and https://www.meteoswiss.admin.ch/home.html?tab=overview) report the full range of the time bucket (e.g. 1400-1700), but 
if we look at the weather with Google half-way between Switzerland and Denmark https://www.google.com/search?q=weather+in+hamburg it says "2 PM" and "5 PM" and "8 PM" and then we generally know that the "2 PM" label means **weather staring at 2 PM until  5 PM**.

Baptists makes this case well for daily averages too. That is generally `T00:00:00.00` not `T23:59:59.99`

**Comment by iosifescu** [comment]
Thanks for the input, much appreciated. For me it still makes sense (from a computer perspective). BTW, the near-real-time GC-Net data was/is also used by pilots flying to Greenland, so if we perform the shift it will look like the data transmission delay will increase with one hour. But if you say that from an environmental perspective it makes more sense, then we are happy to make the shift (I will probably meet with Derek on Thursday, so we can also discuss this issue).

**Comment by bavay** [comment]
It has nothing to do with polar data, but on our stations (IMIS, ENET, etc networks, so more than 140 stations) it is either an instantaneous measurement (so the data at 12:00 has really been measured at exactly 12:00:00) or an average over the completed period. Interestingly, MeteoCH does it the other way around as what we do... (although we run some of these networks together and therefore exchange the data). I think here there is no proper way of doing it, just the need for more metadata (like the "smp", "avg" fields of Campbell data loggers).

**Comment by iosifescu** [comment]
Thanks for chiming in Mathias - I see a pattern here: at WSL and SLF we tend to think quite alike, so it is either 1) an organisational bias or more probably 2) things were implemented by computer scientists ;-)
Anyway, since MeteoSuisse, PROMICE and Google seem to have another approach, we might be in the minority. So it would be OK for me to change our approach for GC-Net (but I will gladly let @houtzd decide that, as he's still the main custodian of GC-Net data).

**Comment by houtzd** [comment]
All,
I see the point of Baptiste. 
Regarding: "near-real-time GC-Net data was/is also used by pilots flying to Greenland" should not be an issue as this is only intermittently used in the summer season when people are flying onto the ice sheet for field work. Maybe we add a note on the display explaining the 1 hour average and timestamp.
If we are all using Campbell loggers is it really a difference in the code running on the logger or is the hour offset applied in post-processing? I am pretty sure that the timestamps of our raw datalogger files correspond directly with the timestamps of the processed (csv or .smet/.nead) files. Does GEUS put the hour offset in during post-processing?

**Comment by mankoff** [comment]
My understanding (limited, may not be correct, can be verified by @dirk-van-as or @robertFausto) is that GEUS `raw` data is at 10 minute intervals and I believe timestamped at the **beginning** of the period. The transmitted data is timestamped at the **end** of the period and then the timestamp is shifted in post-processing.

The code that implements this shift: https://github.com/GEUS-PROMICE/PROMICE-AWS-processing/blob/dd896626e9a4efa38781865de568ac4a377669d8/IDL/AWSdataprocessing_v3.pro#L254

My documentation (with some graphics) of the PROMICE workflow: https://github.com/GEUS-PROMICE/PROMICE-AWS-processing

**Comment by mankoff** [comment]
As per conversation with @robertfausto, the `raw` data (10 minute sampling) is **instantaneous** timestamp, except for the windspeed which collected and timestamped at at the **end of the 10 min window**. Our post-processing, linked above, then shifts timestamps to the beginning of the period.

**Comment by mankoff** [comment]
I think who (of us) does what shouldn't matter. This should be defined by the WMO. Perhaps @citterio knows if timestamps should represent the beginning or end of the sample period?

After a quick search I'm not sure about the WMO, but it appears from https://www.weather.gov/tg/time that the US government standard  is:

    The time expressed in surface observations is the time the observation is completed.

And that page suggests this is adopted from a larger international standard.

**Comment by iosifescu** [comment]
Interesting, many thanks for the information Ken! 
I tried to search the web a bit, but came ended up even more confused as before, see for example the weird content of http://codes.wmo.int/wmdr/TimeStampMeaning
If we don't clarify the WMO viewpoint in October, then in November Mathias and I will participate at the WMO data conference, so maybe we can find an expert there that we can ask.

**Comment by ghost** [comment]
As with many other things, the WMO way is to make the intended meaning explicit rather than mandate some arbitrary convention or another. For time stamps the [WIGOS Metadata Standard](https://library.wmo.int/doc_num.php?explnum_id=10109) chapter 7, category 7 'Data processing and reporting', optional field 7-09 'Aggregation period' refers to [code table 11-03 'Meaning of time stamp'](http://codes.wmo.int/wmdr/TimeStampMeaning), which allows beginning, end, middle, inapplicable and unknown.

Campbell dataloggers write to memory tables with the timestamp of the nominal end of the aggregation period. Nominal means that the last measurement routine in the aggregation period must be concluded before data is aggregated and written. So a record with timestamp at 12:00:00 includes values from the measurement routine started at 12:00:00. For PROMICE this happens once every 10 minutes so each 10 minutes record is aggregated over that 1 single measurement and the values are instantaneous matching the timestamp. This ignoring the time required for scanning all sensors during each measurement routine (ca. 10 seconds), and the physical time constant of the sensor response (seconds to minutes) and wind speed which is integrated over the entire 10 minutes. However wind direction is instantaneous at the time of the timestamp. 

Most of the PROMICE transmitted values are aggregated over the entire period since the previous transmission, so hourly transmissions are aggregated over the 6 10-minutes measurement in the hour ending with the transmitted timestamp. There are some exceptions for various reasons, such as GPS coordinates and (I think) snow height. A few parameters are transmitted both as aggregated and as instantaneous values, so for those fields the transmitted timestamp matches the instantaneous measurement.

i'm not too familiar with what happens later in postprocessing.

**Comment by iosifescu** [comment]
@citterio thanks for the info. BTW, if you have contacts with WMO, could you tell them to correct the descriptions in [code table 11-03](http://codes.wmo.int/wmdr/TimeStampMeaning)? Because even if we understand what they mean, the descriptions are garbled and therefore confusing. (E.g. Beginning indicates the end of a period, End indicates the middle of a period).

**Comment by mankoff** [comment]
OK - well without a standard to tell us what to do, we need to choose one. And perhaps first choose how to choose one (Voting? Deferring to PM? Using the mode of others behavior?).

I'm in favor of beginning-of-period for the following reasons:

1) That's how most consumer-level weather applications do it - If you have an iPhone or Android phone and look at the weather app there, if it isn't explicit t0-t1 buckets, then it usually labels an hour and (I think?) it is implied that the weather icon depicts what it is likely to be for that hour - that is, the time following the timestamp.

2) Graphically, we generally label times on the x-axis as `0, 1, 2` and it is understood that the information following the `0` label prior to the `1` label is in the `0` hour.

3) When moving to larger times, end-of-time becomes very confusing, and with beginning-of-time labels can be shorter. Think about an annual average. Is the value associated with timestamp `2012` the 2012 annual average? Almost certainly yes. If the data paired with `2012` is the 2011 annual average, it would be confusing. If you want to properly label beginning-of-time then `2012`, `2012-01`, or `2012-01-01` is sufficient, because the missing part is implied as the smallest (e.g. `01-01 T 00:00:00`). If you want to properly label end-of-time, then you should label `2011-12-31 23:59:59.99` and carry that level of detail everywhere.

**Comment by iosifescu** [comment]
OK @mankoff - your reasoning makes sense and a shift is easy to implement (but suggest to introduce a timestamp_meaning key in the NEAD specs - see separate issue).

**Comment by Dirk-van-As** [comment]
My 2 cents... The PROMICE hourly data are indeed shifted back by an hour (so that the 14:00 average covers the 14:00-15:00 period) because also daily, monthly and yearly average timestamps represent the period during which is was taken. The main confusion is actually that we are all used to seeing time-of-day notations with minutes included (00): 14:00 vs 14h values.

For those users interested in instantaneous values such as pilots, they can use the instantaneous data appended to AWS transmissions. Downside is that they're not appended every hour in our case... Or we just shift the data forward in time again only for the purpose of plotting online?

**Comment by BaptisteVandecrux** [comment]
Just had a look at the latest files. Thanks for switching the time stamping standard. 
The addition of `# timestamp_meaning = beginning` make it clear to the file user.

**Comment by iosifescu** [comment]
You're welcome. The data in the database is still in the GC-Net standard (accumulated over past hour), but we can export it through the API with both timestamp_meaning = beginning and timestamp_meaning = end. This way, we support both options, while enabling us to also easily support in the future the timestamp_meaning = instantaneous with almost no additional code except a simple configuration change. 
Anyway, thank you for drawing our attention to these issues because it also leads to improved NEAD specs. And everybody profits when having robust NEAD specifications! So please continue to report any errors or ideas for further improvement, thanks a lot!
